### ISSUE TITLE
Add ability to add *referrer* to create reservation

### ISSUE THREAD

**Issue by tgoldenberg** [nikolenkoanton92/node_waitlisted#1]
I am using waitlisted with a custom UI, so not using their modal. I am creating a user via the API. I would like to add the referral code when creating a reservation, so as to pass points to the referrer. I tried adding `refferer` to the request body, but now I see that it is not possible. Is it possible to add this as a param to enable the desired outcome? Thank you!

**Comment by nikolenkoanton92** [comment]
Hello @tgoldenberg,

I am not sure if waitlisted api support this.

Thanks,
Anton

**Comment by tgoldenberg** [comment]
Yes, it is possible.
```
fetch('https://DOMAIN.app.waitlisted.co/api/v1/reservation', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/x-www-form-urlencoded',
  }, 
  body: 'reservation[email]=EMAIL&reservation[refcode]=REFCODE'
});
```

**Comment by tgoldenberg** [comment]
And without the ability to add the `refcode` in, the API is almost useless, IMO

**Comment by nikolenkoanton92** [comment]
sweet, I can update package on weekend or you can send PR to make this faster.

Thanks,
Anton

**Comment by nikolenkoanton92** [comment]
@tgoldenberg package is published. I will close this issue. Thank you for improvements.
